version: '3.0'

services:
  main:
    container_name: main
    build: 
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    env_file:
      - .development.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-js-learn
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql/
    restart: always